---
- name: Install Nginx
  apt:
    name: nginx
    state: present

- name: Copy site.html file
  copy:
    src: site.html
    dest: /usr/share/nginx/html/site.html
    owner: root
    group: root
    mode: "0644"

- name: Restart Nginx
  service:
    name: nginx
    state: restarted
