---
- name: Instalação e Configuração do Nginx
  hosts: localhost
  become: yes

  tasks:
    - name: Instalar o Nginx
      apt:
        name: nginx
        state: present

    - name: Copiar o arquivo site.html
      copy:
        src: ./site.html
        dest: /usr/share/nginx/html/site.html
