---
- name: Instalação e Configuração do Nginx
  hosts: all
  become: yes

  tasks:
    - name: Instalar o Nginx
      apt:
        name: nginx
        state: present

    - name: Copiar o arquivo site.html
      copy:
        src: /caminho/para/o/arquivo/site.html
        dest: /var/www/html/site.html
